--- #YAML:1.0
name:                Lingua-Flags
version:             0.03
abstract:            Provide small flag icons
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Mime::Base64:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Alberto Simoes <ambs@cpan.org>
