--- #YAML:1.0
name:                Lingua-Flags
version:             0.05
abstract:            Provide small flag icons
license:             ~
author:              
    - Alberto Simoes <ambs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    MIME::Base64:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
